version: 3.7
services:
  reader:
      image: golang:1.12
      container_name: csv_reader
      init: true
      volumes:
         - type: bind
           source: ./csv
           target: /tmp/csv
         - type: bind
           source: ./reader
           target: /srv/reader
      working_dir: /srv
      restart: always 
      networks:
         - app
  crm:
      image: golang:1.12
      container_name: crm_integrator
      init: true
      volumes:
         - type: bind
           source: ./crm
           target: /srv/crm
      working_dir: /srv
      restart: always  
      networks:
         - app  
  db:
      image: postgres:10.10
      ports:
         - "8001:5432"
      networks:
         - app
      environment:
         POSTGRES_USER: ${PG_USER}
         POSTGRES_PASSWORD: ${PG_PWD}
  nginx:
      image: nginx:1.16.1
      ports:
         - "80:80"
         - "443:443"
networks:
      - app